# Generated by Django 5.0.6 on 2024-05-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
