# Generated by Django 5.0.6 on 2024-05-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framerinfo',
            name='user_m',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.DeleteModel(
            name='BuyersInfo',
        ),
        migrations.DeleteModel(
            name='FramerInfo',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
