# Generated by Django 5.0.6 on 2024-05-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophouse', '0004_remove_checkoutinfo_cart_checkoutinfo_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='checkout_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shophouse.checkoutinfo'),
        ),
    ]
