# Generated by Django 5.0.6 on 2024-05-29 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeruser',
            name='Profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BuyerUser', to='authenticate.profile'),
        ),
        migrations.AlterField(
            model_name='frameruser',
            name='Profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FramerUser', to='authenticate.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_m',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
