# Generated by Django 5.0.6 on 2024-05-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_buyeruser_profile_alter_frameruser_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeruser',
            name='Profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyeruser', to='authenticate.profile'),
        ),
        migrations.AlterField(
            model_name='frameruser',
            name='Profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frameruser', to='authenticate.profile'),
        ),
    ]
