# Generated by Django 5.0.6 on 2024-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_buyeruser_profile_alter_frameruser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_framer',
            field=models.BooleanField(default=0),
        ),
    ]
